export default [
  {
    title: 'Portfolio',
    descriptionParagraphs: [
      'This site, built to showcase my work featuring filterable projects list.',
      'Constructed using Next.js and Materialize.',
    ],
    image: 'portfolio.png',
    filters: ['NextJS', 'Frontend', 'React', 'Redux', 'Materialize'],
    url: 'https://www.alasdairmoffat.com',
    repository: 'https://github.com/alasdairmoffat/Portfolio',
  },
  {
    title: 'Giant Bomb Video Downloader',
    descriptionParagraphs: [
      'Polls Giant Bomb API for most recent videos and downloads any uploaded since last download.',
      'Supports partial download resumption and allows videos to be manually skipped.',
    ],
    image: 'giantbomb-downloader.png',
    filters: ['Backend', 'Python', 'SQLite'],
    url: 'https://raw.githubusercontent.com/alasdairmoffat/Giant-Bomb-Downloader/master/gb_dl.py?token=AMMODFKYLPMMMGNBNCFZP2S7QXOWW',
    repository: 'https://github.com/alasdairmoffat/Giant-Bomb-Downloader',
  },
  {
    title: 'Image Search Abstraction',
    descriptionParagraphs: [
      'Search images from imgur.com.',
      'Results are paginated and most recent searched strings can be viewed.',
    ],
    image: 'image-search-abstraction.png',
    filters: [
      'Fullstack',
      'Frontend',
      'Backend',
      'Express',
      'React',
      'Redux',
      'MongoDB',
      'Bootstrap',
      'Mocha & Chai',
    ],
    url: 'https://mern-image-search-abstraction.herokuapp.com/',
    repository: 'https://github.com/alasdairmoffat/Image-Search-Abstraction',
  },
  {
    title: 'Sudoku Solver',
    descriptionParagraphs: [
      'Progressive Web App Sudoku Solver.',
      'Solves any given sudoku puzzle and can be installed to mobile devices for offline use.',
    ],
    image: 'sudoku-solver.png',
    filters: ['Frontend', 'React', 'Sass', 'Web Workers', 'PWA'],
    url: 'https://alasdairmoffat.github.io/Sudoku-Solver/',
    repository: 'https://github.com/alasdairmoffat/Sudoku-Solver',
  },
  {
    title: 'Anonymous Message Board',
    descriptionParagraphs: [
      'A simple message board featuring threads and replies.',
      'Threads and replies can be created, deleted and reported.',
    ],
    image: 'anonymous-message-board.png',
    filters: [
      'Fullstack',
      'Frontend',
      'Backend',
      'Express',
      'MongoDB',
      'Mocha & Chai',
    ],
    url: 'https://alasdairmoffat-anonymous-message-board.glitch.me/',
    repository: 'https://github.com/alasdairmoffat/Anonymous-Message-Board',
  },
  {
    title: 'Stock Price Checker',
    descriptionParagraphs: [
      'Check stock prices on one ticker, or compare two tickers.',
      'Tickers can be favourited, and number of favourites will be displayed.',
    ],
    image: 'stock-price-checker.png',
    filters: [
      'Fullstack',
      'Frontend',
      'Backend',
      'Express',
      'MongoDB',
      'Mocha & Chai',
    ],
    url: 'https://alasdairmoffat-stock-price-checker.glitch.me/',
    repository: 'https://github.com/alasdairmoffat/Stock-Price-Checker',
  },
];
